# Generated by Django 5.0.7 on 2024-07-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Erika_Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_Image', models.ImageField(upload_to='ProfileImg')),
            ],
        ),
    ]
