# Generated by Django 5.0.7 on 2024-08-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Erika_Admin', '0002_profile_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receive_Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('Messages', models.TextField()),
            ],
        ),
    ]
