# Generated by Django 5.0.7 on 2024-08-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Erika_Admin', '0006_aboutme_paragraph_1_alter_aboutme_erika_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Books_Images', models.ImageField(upload_to='Media')),
                ('Book_Link', models.CharField(max_length=200)),
                ('Descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reviews', models.TextField()),
            ],
        ),
    ]
