# Generated by Django 5.0.7 on 2024-10-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Erika_Admin', '0007_books_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author_Image', models.ImageField(upload_to='Media')),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='Author_Image',
        ),
    ]
