# Generated by Django 5.0.7 on 2024-10-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Erika_Admin', '0008_profile_image_remove_aboutme_author_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile_Image',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='Author_Image',
            field=models.ImageField(blank=True, upload_to='Media'),
        ),
    ]
