# Generated by Django 5.0 on 2024-06-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErikaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookErika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('EventDescription', models.TextField()),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone', models.CharField(max_length=10)),
            ],
        ),
    ]
