# Generated by Django 5.0 on 2024-06-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErikaApp', '0002_bookerika'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Info_Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
