# Generated by Django 5.0 on 2024-07-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErikaApp', '0005_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
