# Generated by Django 5.0.7 on 2024-07-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErikaApp', '0009_profile_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_images',
            name='profile_Image',
            field=models.ImageField(upload_to='ProfileImg'),
        ),
    ]
