# Generated by Django 5.0.7 on 2024-07-25 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ErikaApp', '0010_alter_profile_images_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile_Images',
        ),
    ]
