# Generated by Django 5.0.7 on 2024-08-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErikaApp', '0011_delete_profile_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookerika',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
